# Basic Information
title: Zhilong Mao
position: Master's Student
affiliation: National University of Defense Technology
affiliation_link: https://www.nudt.edu.cn/
email: mzl02@nudt.edu.cn

# Search Engine Optimization (SEO)
keywords: Zhilong Mao, computer vision, few-shot learning, class-incremental learning, causal representation learning
description: Academic homepage of Zhilong Mao, a researcher in few-shot learning, class-incremental learning, causal representation learning, and computer vision.
canonical: https://zl2811.github.io/

# Links
cv_link: https://docs.google.com/document/d/1h4gtP4R8yYCK2FPlQ885y6qCOt2NKGel33hRMkhgtNA/edit?tab=t.0
github_link: https://github.com/zl2811
wechat_qr: /assets/img/wechat_qr.jpg

# Images
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: true

# Appearance
auto_dark_mode: true
font: "Serif"

# Theme
remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
